// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mloglik1c
double mloglik1c(NumericVector jtms, double TT, Function nu, NumericVector gcoef, Function Inu);
RcppExport SEXP IHSEP_mloglik1c(SEXP jtmsSEXP, SEXP TTSEXP, SEXP nuSEXP, SEXP gcoefSEXP, SEXP InuSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type jtms(jtmsSEXP);
    Rcpp::traits::input_parameter< double >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< Function >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcoef(gcoefSEXP);
    Rcpp::traits::input_parameter< Function >::type Inu(InuSEXP);
    __result = Rcpp::wrap(mloglik1c(jtms, TT, nu, gcoef, Inu));
    return __result;
END_RCPP
}
// mloglik1d
double mloglik1d(NumericVector jtms, double TT, Function nu, NumericVector gcoef, Function Inu);
RcppExport SEXP IHSEP_mloglik1d(SEXP jtmsSEXP, SEXP TTSEXP, SEXP nuSEXP, SEXP gcoefSEXP, SEXP InuSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type jtms(jtmsSEXP);
    Rcpp::traits::input_parameter< double >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< Function >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcoef(gcoefSEXP);
    Rcpp::traits::input_parameter< Function >::type Inu(InuSEXP);
    __result = Rcpp::wrap(mloglik1d(jtms, TT, nu, gcoef, Inu));
    return __result;
END_RCPP
}
// mloglik1e
double mloglik1e(NumericVector jtms, double TT, NumericVector nuvs, NumericVector gcoef, double InuT);
RcppExport SEXP IHSEP_mloglik1e(SEXP jtmsSEXP, SEXP TTSEXP, SEXP nuvsSEXP, SEXP gcoefSEXP, SEXP InuTSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type jtms(jtmsSEXP);
    Rcpp::traits::input_parameter< double >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nuvs(nuvsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcoef(gcoefSEXP);
    Rcpp::traits::input_parameter< double >::type InuT(InuTSEXP);
    __result = Rcpp::wrap(mloglik1e(jtms, TT, nuvs, gcoef, InuT));
    return __result;
END_RCPP
}
